### ISSUE TITLE
getEbayDetails not retrieving all nodes

### ISSUE THREAD

**Issue by dtjones** [davidtsadler/ebay-sdk-trading#11]
im trying to get the "UnitOfMeasurementDetails" node but even when adding 

    $request->getDetailName('UnitOfMeasurementDetails');

its still missing.

**Comment by davidtsadler** [comment]
As stated in the eBay documentation [DetailName](http://developer.ebay.com/DevZone/XML/docs/Reference/ebay/GeteBayDetails.html#Request.DetailName) is a repeatable field which allows you to specify it more than once in the request. E.g.

```xml
<GeteBayDetailsRequest>
    <DetailName>CountryDetails</DetailName>
    <DetailName>ReturnPolicyDetails</DetailName>
    <DetailName>UnitOfMeasurementDetails</DetailName>
</GeteBayDetailsRequest>
```

The SDK handles this by treating the field as an array like property of the request object.

```php
$request = new Types\GeteBayDetailsRequestType();
// Notice that we use [] because DetailName is array like and we are pushing values into it.
$request->DetailName[] = 'CountryDetails';
$request->DetailName[] = 'ReturnPolicyDetails';
$request->DetailName[] = 'UnitOfMeasurementDetails';
```

Because the property is array like we can also do the following by assigning an array.

```php
// Notice that we no longer need [] because we are assigning an array to the property.
$request->DetailName= ['CountryDetails', 'ReturnPolicyDetails', 'UnitOfMeasurementDetails'];
```

**Comment by dtjones** [comment]
Thanks @davidtsadler, your comment was very useful. Much appreciated.
