### ISSUE TITLE
Get Description for GetItem

### ISSUE THREAD

**Issue by baskettcase** [davidtsadler/ebay-sdk-trading#12]
I changed Trading/Types/GetItemRequestType.php to include the DetailLevel in the API:

        'DetailLevel' => array(
            'type' => 'string',
            'unbound' => false,
            'attribute' => false,
            'elementName' => 'DetailLevel'
        ),

This allows the item to return the description etc. Is there another way of doing this with your existing code so that I am not modifying your code? I might be missing the proper way of doing this. :)

**Comment by davidtsadler** [comment]
DetailLevel is a property of [AbstractRequestType](https://github.com/davidtsadler/ebay-sdk-trading/blob/master/src/DTS/eBaySDK/Trading/Types/AbstractRequestType.php#L50) which [GetItemRequestType](https://github.com/davidtsadler/ebay-sdk-trading/blob/master/src/DTS/eBaySDK/Trading/Types/GetItemRequestType.php#L37) extends.

As stated in the eBay documentation [ DetailLevel](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetItem.html#Request.DetailLevel) is a repeatable field which allows you to specify it more than once in the request. E.g.

```
<GetItemRequest>
    <DetailLevel>ItemReturnAttributes</DetailLevel>
    <DetailLevel>ItemReturnDescription</DetailLevel>
</GetItemRequest>
```

The SDK handles this by treating the field as an array like property of the request object. 

```
$request = new Types\GetItemRequestType();
// Notice that we use [] because DetailLevel is array like and we are pushing values into it.
$request->DetailLevel[] = 'ItemReturnAttributes';
$request->DetailLevel[] = 'ItemReturnDescription';
```

Because the property is array like we can also do the following by assigning an array.

```
// Notice that we no longer need [] because we are assigning an array to the property.
$request->DetailLevel = ['ItemReturnAttributes', 'ItemReturnDescription'];
```

**Comment by baskettcase** [comment]
Ah thank you. It looked like it was a string, not an array. I appreciate the help!
