### ISSUE TITLE
Category id exceeds max php integer value

### ISSUE THREAD

**Issue by snky1987** [davidtsadler/ebay-sdk-trading#23]
Today I noticed that maximum PHP Integer value is: 2147483647 while a lot of 3rd level eBay (custom) categories exceed this value.

In 2007 eBay changed categoryID form Int to Long:
ver. 499 date. 2007-02-07 	
RootCategoryID, Store.CustomCategories.CustomCategory.CategoryID, Store.HomePage (modified): The data types for IDs used for eBay Stores have changed from xs:int to xs:long to prepare for future increases in ID values.

Which causes issues while getting categories form eBay. I soreted it out by changing 'Integer' to 'String' as temporary fix but it may b useful to change it with a long shot solution :)

**Comment by davidtsadler** [comment]
Hello,

Sadly this issue has been [raised before](https://github.com/davidtsadler/ebay-sdk-trading/issues/6) and for the time been the [README](https://github.com/davidtsadler/ebay-sdk-trading/blob/master/README.md#requirements) is recommending using the 64 bit version of PHP due to [the issue](http://devbay.net/sdk/guides/requirements/#issues).

Changing the type to string is something that I'm considering once version 1.0 is released.
